# Generated by Django 2.2.24 on 2024-03-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('city', models.CharField(choices=[('BEER', 'Beer Sheva'), ('ASD', 'Ashdod'), ('ASHQ', 'Ashkelon'), ('NEOT', 'Netivot'), ('OFK', 'Ofakim'), ('SDR', 'Sderot'), ('KRM', 'Kiryat Malachi'), ('KSP', 'Kiryat Gat'), ('NPM', 'Netiv HaAsara'), ('REH', 'Rehovot'), ('OME', 'Omer'), ('MET', 'Metar'), ('RAH', 'Rahat'), ('LAk', 'Lakiya'), ('HURA', 'Hura'), ('HOL', 'Holon'), ('KSI', 'Ksifa'), ('DEM', 'Dimona'), ('ARAD', 'Arad')], max_length=5)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='report_pictures/')),
            ],
            options={
                'db_table': 'addreport',
            },
        ),
        migrations.CreateModel(
            name='Workerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workerlogin',
            },
        ),
    ]
